### ISSUE TITLE
[iOS] Youtube avatar images are unable to display in home page.

### ISSUE THREAD

**Issue by lvscar** [bigzhu/english_buoy#31]
<img width="422" alt="Screen Shot 2020-02-12 at 3 57 56 PM" src="https://user-images.githubusercontent.com/1578838/74314526-863dc780-4db0-11ea-9eda-05042d8af410.png">

Error information:
```
flutter: ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
flutter: The following SocketException was thrown resolving an image codec:
flutter: OS Error: Operation timed out, errno = 60, address = lh3.googleusercontent.com, port = 61562
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:84:41)
flutter: <asynchronous suspension>
flutter: #1      NetworkImage.load (package:flutter/src/painting/_network_image_io.dart:47:14)
flutter: #2      ImageProvider.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:327:17)
flutter: #3      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:197:22)
flutter: #4      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:325:84)
flutter: #5      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:41:29)
flutter: #6      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:323:11)
flutter: #10     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:315:16)
flutter: #11     DecorationImagePainter.paint (package:flutter/src/painting/decoration_image.dart:240:55)
flutter: #12     _BoxDecorationPainter._paintBackgroundImage (package:flutter/src/painting/box_decoration.dart:463:19)
flutter: #13     _BoxDecorationPainter.paint (package:flutter/src/painting/box_decoration.dart:481:5)
flutter: #14     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2020:16)
flutter: #15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #17     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #20     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
flutter: #21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #23     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #25     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #26     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #27     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #28     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #29     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #30     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #31     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #32     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2515:15)
flutter: #33     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:404:5)
flutter: #34     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #35     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #36     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
flutter: #37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #39     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #40     PaintingContext.pushClipRect.<anonymous closure> (package:flutter/src/rendering/object.dart:450:83)
flutter: #41     ClipContext._clipAndPaint (package:flutter/src/painting/clip.dart:29:12)
flutter: #42     ClipContext.clipRectAndPaint (package:flutter/src/painting/clip.dart:57:5)
flutter: #43     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:450:7)
flutter: #44     RenderClipRect.paint (package:flutter/src/rendering/proxy_box.dart:1330:23)
flutter: #45     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #46     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #47     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
flutter: #48     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #49     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #50     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
flutter: #51     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #52     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #53     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #54     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #55     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #56     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #57     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:531:11)
flutter: #58     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #59     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #60     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #61     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:391:12)
flutter: #62     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1799:15)
flutter: #63     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #64     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #65     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #66     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:391:12)
flutter: #67     RenderAnnotatedRegion.paint (package:flutter/src/rendering/proxy_box.dart:5079:13)
flutter: #68     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #69     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #70     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #71     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #72     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #73     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #74     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #75     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #76     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2515:15)
flutter: #77     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:404:5)
flutter: #78     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #79     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #80     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #81     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:531:11)
flutter: #82     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #83     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #84     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #85     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:391:12)
flutter: #86     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1799:15)
flutter: #87     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #88     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #89     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
flutter: #90     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
flutter: #91     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
flutter: #92     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
flutter: #93     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:981:29)
flutter: #94     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:403:19)
flutter: #95     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:797:13)
flutter: #96     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
flutter: #97     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1109:15)
flutter: #98     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1048:9)
flutter: #99     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:964:5)
flutter: #103    _invoke (dart:ui/hooks.dart:260:10)
flutter: #104    _drawFrame (dart:ui/hooks.dart:218:3)
flutter: (elided 6 frames from package dart:async)
flutter:
flutter: Image provider:
flutter:   NetworkImage("https://lh3.googleusercontent.com/a-/AAuE7mCs1HpLmreQfKKSdxV9bCPjUl5aHX9EJqLlcds8fg=s1337",
flutter:   scale: 1.0)
flutter: Image key:
flutter:   NetworkImage("https://lh3.googleusercontent.com/a-/AAuE7mCs1HpLmreQfKKSdxV9bCPjUl5aHX9EJqLlcds8fg=s1337",
flutter:   scale: 1.0)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: Couldn't download or retrieve file.
flutter: Another exception was thrown: Couldn't download or retrieve file.
flutter: Another exception was thrown: Couldn't download or retrieve file.
```

I think my proxy setting is active. ( I have tried the global proxy mode on my computer ,the same error still here).

**Comment by bigzhu** [comment]
Same as this: https://github.com/flutter/flutter/issues/26789

Even I set mac system proxy, flutter app in simulator still use direct connections
